# Generated by Django 4.2.7 on 2023-11-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
    ]
